apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pg-clusters
  namespace: argocd
  labels:
    component: pg-database
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: platform
  source:
    repoURL: https://github.com/usernamenenad/homelab.git
    path: infra/pg-clusters
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: pg-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    ignoreDifferences:
      - group: postgresql.cnpg.io
        kind: Cluster
        jsonPointers:
          - /spec/instances
