apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-pgadmin
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: apps
  source:
    repoURL: https://github.com/usernamenenad/homelab.git
    path: apps/pgadmin
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: apps-pgadmin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
