apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
  labels:
    component: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: platform
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: promtail
    targetRevision: "*"
    helm:
      values: |
        config:
          clients:
            - url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
          snippets:
            pipelineStages:
              - cri: {}
        tolerations:
          - effect: NoSchedule
            operator: Exists
        resources:
          requests:
            memory: 64Mi
            cpu: 25m
          limits:
            memory: 256Mi
            cpu: 100m
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
