apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: istio-ingress
data:
  config.yaml: |
    tunnel: 16ace56f-e182-44a5-9adf-5d1fe455ad08
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true

    originRequest:
      noTLSVerify: false
      originServerName: nenad.cloud

    ingress:
      - hostname: "*.nenad.cloud"
        service: https://istio-ingressgateway.istio-ingress.svc.cluster.local:443
      - hostname: nenad.cloud
        service: https://istio-ingressgateway.istio-ingress.svc.cluster.local:443
      - service: http_status:404
