apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    component: argocd
spec:
  project: platform
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: "*"
    helm:
      values: |
        server:
          extraArgs:
            - --insecure

        configs:
          cm:
            url: https://argocd.nenad.cloud
            oidc.config: |
              name: Homelab
              issuer: https://login.microsoftonline.com/c4004238-4e8c-4297-95f8-a776f05a1bd8/v2.0
              clientId: ec22b838-f2dd-42b6-a472-4fd0e730e884
              clientSecret: $oidc.entra.clientSecret
              requestedScopes:
                - openid
                - profile
                - email
              requestedIDTokenClaims:
                groups:
                  essential: true

          rbac:
            policy.csv: |
              g, a5913b87-0ce6-4a96-ab74-266936a3c4e1, role:admin
            policy.default: role:readonly
            scopes: '[groups, email]'

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: argocd-secret
      jsonPointers:
        - /data/oidc.entra.clientSecret
