apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: platform
  source:
    repoURL: https://github.com/usernamenenad/homelab.git
    path: infra/argocd-resources
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
