apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    component: longhorn
spec:
  project: platform
  source:
    repoURL: https://github.com/usernamenenad/homelab.git
    path: infra/longhorn-resources
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
