apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  admin.enabled: "false"
  url: https://argocd.nenad.cloud
  oidc.config: |
    name: Azure
    issuer: https://login.microsoftonline.com/c4004238-4e8c-4297-95f8-a776f05a1bd8/v2.0
    clientID: c15f4fb3-3445-4e3e-86e4-ba369eed56b3
    clientSecret: $argocd-oidc-secret:oidc.azure.clientSecret
    requestedScopes:
      - openid
      - profile
      - email
    requestedIDTokenClaims:
      groups:
        essential: true
      email:
        essential: true
      upn:
        essential: true
    usernameClaim: preferred_username
