apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: gateway
    targetRevision: 1.22.0
    helm:
      skipSchemaValidation: true
      values: |
        service:
          annotations:
            load-balancer.hetzner.cloud/location: "nbg1"
            load-balancer.hetzner.cloud/use-private-ip: "true"
            load-balancer.hetzner.cloud/name: "homelab-lb"
            load-balancer.hetzner.cloud/protocol: "tcp"
            load-balancer.hetzner.cloud/uses-proxyprotocol: "false"
          ports:
            - name: status-port
              port: 15021
              protocol: TCP
              targetPort: 15021
            - name: http2
              port: 80
              protocol: TCP
              targetPort: 8080
            - name: https
              port: 443
              protocol: TCP
              targetPort: 8443
        nodeSelector:
          node-role.kubernetes.io/control-plane: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
