apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-cluster-affine
  namespace: pg-cluster-affine
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  instances: 3

  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "256MB"

  bootstrap:
    initdb:
      database: affine
      owner: affine
      secret:
        name: pg-cluster-affine-creds

  storage:
    size: 10Gi
    storageClass: longhorn

  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "500m"
